In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('movies_metadata.csv')

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [6]:
df.shape

(45466, 24)

In [7]:
df.duplicated().sum()

np.int64(13)

In [8]:
df = df.drop_duplicates().reset_index(drop=True)

In [9]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [10]:
df = df[['title', 'overview', 'genres', 'tagline', 'vote_average', 'popularity']]

In [11]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [12]:
df = df.dropna(subset=['title'])

In [13]:
df['overview'] = df['overview'].fillna('')

In [14]:
import ast
df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]))

In [15]:
df['tagline'] = df['tagline'].fillna('')

In [16]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [17]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [18]:
df['vote_average'] = df['vote_average'].fillna(df['vote_average'].mean())

In [19]:
df['popularity'] = df['popularity'].fillna(df['popularity'].mode())

In [20]:
df.isna().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [21]:
df['tags'] = df['overview']+df['genres']+df['tagline']

In [22]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [23]:
df = df.reset_index(drop=True)

In [24]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()

In [25]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [26]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [27]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91935\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [30]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [31]:
tfidf_matrix.shape

(45447, 50000)

In [32]:
# Apply string methods to Series using .str accessor
# Then tokenize each row individually using apply()
df['tags'] = df['tags'].str.lower().apply(nltk.word_tokenize)

# Alternative approach if you want to tokenize the entire column as one string:
# df['tags'] = nltk.word_tokenize(' '.join(df['tags'].str.lower()))

In [33]:
stop_words = set(stopwords.words('english'))

In [34]:
df['tags'] = df['tags'].apply(lambda words: [w for w in words if w not in stop_words])

In [35]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [36]:
df['tags']

0        [led, woody, ,, andy, 's, toys, live, happily,...
1        [siblings, judy, peter, discover, enchanted, b...
2        [family, wedding, reignites, ancient, feud, ne...
3        [cheated, ,, mistreated, stepped, ,, women, ho...
4        [george, banks, recovered, daughter, 's, weddi...
                               ...
45442    [rising, falling, man, woman.drama, familyrisi...
45443    [artist, struggles, finish, work, storyline, c...
45444    [one, hits, goes, wrong, ,, professional, assa...
45445    [small, town, live, two, brothers, ,, one, min...
45446    [50, years, decriminalisation, homosexuality, ...
Name: tags, Length: 45447, dtype: object

In [37]:
vocab = sorted(set([word for tag_list in df['tags'] for word in tag_list]))

In [38]:
# similarity = linear_kernel(tfidf_matrix, tfidf_matrix) this will kill

from sklearn.metrics.pairwise import linear_kernel

from sklearn.metrics.pairwise import linear_kernel

def recommend(title, n=10):
    if title not in indices:
        return ["Movie not found"]

    idx = indices[title]

    # Compute similarity only for this movie → SAFE!
    sim_scores = linear_kernel(tfidf_matrix[idx], tfidf_matrix).flatten()

    # Sort by score
    similar_indices = sim_scores.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_indices].tolist()

In [39]:
recommend("Comic Book Confidential", 10)

['The Image Revolution',
 'The Cartoonist: Jeff Smith, BONE and the Changing Face of Comics',
 'Chico Xavier',
 'Independents',
 'Stripped',
 'With Great Power: The Stan Lee Story',
 'Richard Pryor: Icon',
 'Katatsumori',
 'Future Shock! The Story of 2000AD',
 'Animal Crackers']

In [40]:
recommend('Avatar')

['Avatar 2',
 'The Inhabited Island',
 'The Three Musketeers',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Stand by Me Doraemon',
 'Thor: Ragnarok',
 'Moontrap: Target Earth',
 'The Matrix',
 'Cave of the Sharks',
 'Shakedown']

In [41]:
import pickle

# Save TF-IDF matrix
pickle.dump(tfidf_matrix, open("tfidf_matrix.pkl", "wb"))

# Save TF-IDF vectorizer
pickle.dump(tfidf, open("tfidf_vectorizer.pkl", "wb"))

# Save dataframe
df.to_pickle("movies_df.pkl")

# Save indices mapping
pickle.dump(indices, open("indices.pkl", "wb"))